# Generated by Django 6.0.4 on 2026-04-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('online', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemonline',
            name='imagem',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
