# Generated by Django 6.0.4 on 2026-04-20 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('qty', models.CharField(default='1', max_length=20)),
                ('unit', models.CharField(choices=[('un', 'Unidade'), ('kg', 'Quilograma'), ('g', 'Grama'), ('L', 'Litro'), ('ml', 'Mililitro'), ('pct', 'Pacote'), ('cx', 'Caixa')], default='un', max_length=10)),
                ('group', models.CharField(choices=[('Geral', 'Geral'), ('Frutas & Verduras', 'Frutas & Verduras'), ('Laticínios', 'Laticínios'), ('Carnes', 'Carnes'), ('Padaria', 'Padaria'), ('Bebidas', 'Bebidas'), ('Limpeza', 'Limpeza'), ('Higiene', 'Higiene'), ('Congelados', 'Congelados'), ('Mercearia', 'Mercearia')], default='Geral', max_length=50)),
                ('checked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Item do Mercado',
                'verbose_name_plural': 'Itens do Mercado',
                'ordering': ['group', 'created_at'],
            },
        ),
    ]
